// Try Catch

const numero1 = 20;
const numero2 = 30;

console.log(numero1)

// Su funcion es ejecutar el codigo y prevernir que por un error la aplicacion se detenga
try {
    console.log(numero3)
} catch (error) {
    console.log(error)
}
console.log(numero2)